# Generated by Django 5.1.2 on 2025-01-29 01:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0004_alter_workoutexercise_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='bio',
        ),
    ]
